/**
 * What the agent says out loud before it says goodbye (docs/propuestas/05).
 *
 * WHY THIS TEXT IS NOT GENERATED BY THE LLM. The acceptance criterion is that
 * the spoken closing carries evidence and not generic praise. Asking the model
 * to "read these two achievements" would put the guarantee in the hands of a
 * sampler; composing the sentence here and handing it to the TTS verbatim
 * (`vapi.say`) makes it a property of the code. It is the same choice
 * `lib/prediction/contrast.ts` makes for the same reason, and it is why the
 * closing is stored in `session_closings` exactly as it was spoken.
 *
 * SPEAKABILITY. Everything here is pronounced, so it carries no markdown, no
 * bullets, no emoji and no parentheses. The evidence sentences already come out
 * of `evidence.ts` as plain Spanish prose with their numbers written the way
 * they are read.
 *
 * WHAT IT MUST NOT DO: name the difficulty level (the student never hears the
 * configuration during a call), congratulate without a number, or say anything
 * about how the student felt. The closing that follows a session where nothing
 * could be measured says so and stops.
 *
 * Pure module: no database, no network.
 */

import {
    SPOKEN_EVIDENCE_COUNT,
    type EvidenceBasis,
    type ProgressEvidence,
    type ProgressEvidenceResult,
} from './evidence.ts';

/**
 * Evidence that may be READ on screen but never SAID.
 *
 * `higher-level-sustained` names the difficulty level, and the system prompt
 * forbids the agent from ever mentioning that levels exist: for the student this
 * is a defense, not a configuration. The closing is still in the agent's voice,
 * so the ban holds until the call is over. The achievement stays in the panel.
 */
const UNSPOKEN_EVIDENCE_BASES: ReadonlySet<EvidenceBasis> = new Set<EvidenceBasis>([
    'higher-level-sustained',
]);

/** Said when the session produced no measurable achievement at all. */
const NO_EVIDENCE_CLOSING =
    'Con esto cerramos la sesión. Esta vez no quedaron respuestas suyas registradas, así que no tengo datos para comentarle. Gracias por su exposición.';

const OPENING = 'Con esto cerramos la sustentación. Antes de despedirme, dos hechos de esta sesión.';

const FAREWELL = 'Gracias por su exposición.';

export interface SessionClosing {
    /** Exactly what is handed to the TTS. Never empty. */
    spokenText: string;
    /** The achievements read out, in the order they are spoken. */
    spoken: ProgressEvidence[];
}

/**
 * Builds the closing from the evidence of the session that is ending.
 *
 * Takes at most `SPOKEN_EVIDENCE_COUNT` items off the top of the already
 * prioritised list, so what the student HEARS is the same evidence, in the same
 * order, as the first lines of what they then READ on screen.
 *
 * NOTE ON TIMING. This runs while the call is still up, so the judge of the
 * post-session report has not evaluated the answers of this session yet and the
 * content and clarity comparisons will normally be absent. That is on purpose:
 * the alternative is making the student wait on a judge run before the agent can
 * say goodbye. The screen shows the fuller list once the answers are evaluated.
 */
export function buildSessionClosing(result: ProgressEvidenceResult): SessionClosing {
    const spoken = result.evidence
        .filter((item) => !UNSPOKEN_EVIDENCE_BASES.has(item.basis))
        .slice(0, SPOKEN_EVIDENCE_COUNT);

    if (spoken.length === 0) {
        return { spokenText: NO_EVIDENCE_CLOSING, spoken: [] };
    }

    const opening =
        spoken.length === 1
            ? 'Con esto cerramos la sustentación. Antes de despedirme, un hecho de esta sesión.'
            : OPENING;

    return {
        spokenText: [opening, ...spoken.map((item) => item.text), FAREWELL].join(' '),
        spoken,
    };
}
